[general]

[default_user]
type=user
admin=no
marked=no
music_on_hold_when_empty=yes
announce_join_leave=yes
dtmf_passthrough=yes

[admin_user]
type=user
admin=yes
marked=yes
announce_join_leave=yes
dtmf_passthrough=yes

[default_bridge]
type=bridge
max_members=10
internal_sample_rate=8000
mixing_interval=20
video_mode=none
